services: 
  - type: web
  name: backend
  env: python
  buildCommand: "./build.sh"        # ensure it's a string
  startCommand: gunicorn server.wsgi:application
  envVars:
  - key: DJANGO_SECRET_KEY
    generateValue: true